import type { BattleCatalog } from './types';

export const harbourlightBattleCatalog: BattleCatalog = {
  techniques: [
    {
      id: 'tideline-jab',
      name: 'Tideline Jab',
      kind: 'strike',
      basePower: 16,
      priority: 2,
      momentumGain: 12,
      momentumCost: 0,
      comboTags: ['tide', 'measured'],
    },
    {
      id: 'watchful-current',
      name: 'Watchful Current',
      kind: 'support',
      basePower: 0,
      priority: 3,
      momentumGain: 22,
      momentumCost: 0,
      comboTags: ['watchful'],
    },
    {
      id: 'shell-turn',
      name: 'Shell Turn',
      kind: 'interrupt',
      basePower: 9,
      priority: 8,
      momentumGain: 4,
      momentumCost: 18,
      comboTags: ['shell-backed'],
      interruptTrigger: 'opponent-strike',
    },
    {
      id: 'reed-vault',
      name: 'Reed Vault',
      kind: 'strike',
      basePower: 15,
      priority: 4,
      momentumGain: 13,
      momentumCost: 0,
      comboTags: ['reed', 'swift'],
    },
    {
      id: 'echo-lure',
      name: 'Echo Lure',
      kind: 'support',
      basePower: 0,
      priority: 2,
      momentumGain: 25,
      momentumCost: 0,
      comboTags: ['echo'],
    },
    {
      id: 'marsh-reversal',
      name: 'Marsh Reversal',
      kind: 'interrupt',
      basePower: 8,
      priority: 9,
      momentumGain: 5,
      momentumCost: 20,
      comboTags: ['reed-runner'],
      interruptTrigger: 'opponent-stance-change',
    },
    {
      id: 'dusk-flare',
      name: 'Dusk Flare',
      kind: 'strike',
      basePower: 18,
      priority: 1,
      momentumGain: 14,
      momentumCost: 0,
      comboTags: ['dusk', 'bloom'],
    },
    {
      id: 'patient-glow',
      name: 'Patient Glow',
      kind: 'support',
      basePower: 0,
      priority: 2,
      momentumGain: 26,
      momentumCost: 0,
      comboTags: ['patient'],
    },
    {
      id: 'quiet-break',
      name: 'Quiet Break',
      kind: 'interrupt',
      basePower: 11,
      priority: 10,
      momentumGain: 3,
      momentumCost: 24,
      comboTags: ['quiet-listener'],
      interruptTrigger: 'opponent-combo',
    },
    {
      id: 'ember-arc',
      name: 'Ember Arc',
      kind: 'strike',
      basePower: 17,
      priority: 2,
      momentumGain: 13,
      momentumCost: 0,
      comboTags: ['ember', 'arc'],
    },
    {
      id: 'hush-step',
      name: 'Hush Step',
      kind: 'support',
      basePower: 0,
      priority: 4,
      momentumGain: 21,
      momentumCost: 0,
      comboTags: ['hush'],
    },
    {
      id: 'counterglow',
      name: 'Counterglow',
      kind: 'interrupt',
      basePower: 10,
      priority: 8,
      momentumGain: 4,
      momentumCost: 18,
      comboTags: ['glow'],
      interruptTrigger: 'opponent-strike',
    },
  ],
  fighterProfiles: [
    {
      speciesId: 'brineling',
      maxVitality: 92,
      power: 18,
      resilience: 16,
      speed: 14,
      techniqueIds: ['tideline-jab', 'watchful-current', 'shell-turn'],
    },
    {
      speciesId: 'reedhorn',
      maxVitality: 104,
      power: 17,
      resilience: 20,
      speed: 11,
      techniqueIds: ['reed-vault', 'echo-lure', 'marsh-reversal'],
    },
    {
      speciesId: 'duskwisp',
      maxVitality: 84,
      power: 22,
      resilience: 12,
      speed: 16,
      techniqueIds: ['dusk-flare', 'patient-glow', 'quiet-break'],
    },
  ],
  combos: [
    {
      id: 'tideglass-pulse',
      name: 'Tideglass Pulse',
      requiredTags: ['tide-glider', 'quiet-listener'],
      minimumContributors: 2,
      momentumCost: 45,
      powerMultiplier: 1.7,
    },
    {
      id: 'marsh-echo-chain',
      name: 'Marsh Echo Chain',
      requiredTags: ['reed-runner', 'echo-caller'],
      minimumContributors: 2,
      momentumCost: 42,
      powerMultiplier: 1.65,
    },
    {
      id: 'night-bloom-chorus',
      name: 'Night Bloom Chorus',
      requiredTags: ['night-bloom', 'patient'],
      minimumContributors: 2,
      momentumCost: 48,
      powerMultiplier: 1.8,
    },
  ],
  contracts: [
    {
      id: 'civic-circuit-opening',
      name: 'Civic Circuit Opening Exhibition',
      venueId: 'civic-circuit-arena',
      opponentTeam: {
        id: 'mira-exhibition-team',
        name: "Mira's Exhibition Team",
        side: 'opponent',
        members: [
          {
            id: 'mira-fallowisp',
            name: 'Fallowisp',
            speciesId: 'fallowisp',
            maxVitality: 88,
            power: 19,
            resilience: 14,
            speed: 15,
            comboTags: ['glow', 'watchful'],
            techniqueIds: ['ember-arc', 'hush-step', 'counterglow'],
          },
        ],
      },
      payout: 85,
      currency: 'CAD',
      maxTurns: 20,
      repeatable: true,
    },
  ],
};
